# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

###### Create all teams ######

# Team.create(level:"Men's pro squad",club:Club.find(3))
# puts Club.find(3).name+"Created"
# Team.create(level:"Men's pro squad",club:Club.find(4))
# Team.create(level:"Men's pro squad",club:Club.find(5))
# Team.create(level:"Men's pro squad",club:Club.find(6))
# Team.create(level:"Men's pro squad",club:Club.find(7))
# Team.create(level:"Men's pro squad",club:Club.find(8))
# Team.create(level:"Men's pro squad",club:Club.find(9))
# Team.create(level:"Men's pro squad",club:Club.find(10))
# Team.create(level:"Men's pro squad",club:Club.find(11))
# Team.create(level:"Men's pro squad",club:Club.find(12))
# Team.create(level:"Men's pro squad",club:Club.find(13))
# Team.create(level:"Men's pro squad",club:Club.find(14))
# Team.create(level:"Men's pro squad",club:Club.find(15))
# Team.create(level:"Men's pro squad",club:Club.find(16))
# Team.create(level:"Men's pro squad",club:Club.find(17))
# Team.create(level:"Men's pro squad",club:Club.find(18))
# Team.create(level:"Men's pro squad",club:Club.find(19))
# Team.create(level:"Men's pro squad",club:Club.find(20))
# Team.create(level:"Men's pro squad",club:Club.find(21))
# Team.create(level:"Men's pro squad",club:Club.find(22))

###### Create all fixtures local ######

# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(16),scorehome:0,scoreaway:0,date:'2020-08-21',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(17),scorehome:0,scoreaway:2,date:'2020-09-17',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(22),awayteam:Team.find(11),scorehome:0,scoreaway:1,date:'2020-08-22',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(5),scorehome:1,scoreaway:1,date:'2020-08-22',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(18),scorehome:2,scoreaway:2,date:'2020-08-23',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(21),scorehome:3,scoreaway:1,date:'2020-08-23',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(7),scorehome:2,scoreaway:1,date:'2020-09-15',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(15),scorehome:4,scoreaway:0,date:'2020-08-23',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(13),scorehome:2,scoreaway:1,date:'2020-08-23',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(12),scorehome:1,scoreaway:0,date:'2020-09-16',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(22),scorehome:4,scoreaway:1,date:'2020-08-28',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(9),scorehome:2,scoreaway:1,date:'2020-08-29',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(3),scorehome:1,scoreaway:0,date:'2020-09-10',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(21),awayteam:Team.find(10),scorehome:0,scoreaway:2,date:'2020-08-29',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(4),scorehome:0,scoreaway:1,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(20),scorehome:2,scoreaway:1,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(14),scorehome:0,scoreaway:2,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(19),scorehome:2,scoreaway:0,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(8),scorehome:0,scoreaway:1,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(6),scorehome:2,scoreaway:3,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(7),scorehome:0,scoreaway:0,date:'2020-09-11',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(10),scorehome:3,scoreaway:1,date:'2020-09-12',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(21),scorehome:2,scoreaway:0,date:'2020-09-12',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(12),scorehome:1,scoreaway:0,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(22),awayteam:Team.find(15),scorehome:0,scoreaway:2,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(18),scorehome:1,scoreaway:0,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(5),scorehome:2,scoreaway:4,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(13),scorehome:2,scoreaway:3,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(16),scorehome:2,scoreaway:1,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(6),scorehome:0,scoreaway:1,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(20),scorehome:0,scoreaway:0,date:'2020-09-18',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(14),scorehome:2,scoreaway:1,date:'2020-09-19',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(8),scorehome:2,scoreaway:1,date:'2020-09-19',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(3),scorehome:0,scoreaway:3,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(21),awayteam:Team.find(22),scorehome:1,scoreaway:0,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(11),scorehome:4,scoreaway:1,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(18),scorehome:2,scoreaway:1,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(19),scorehome:3,scoreaway:2,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(17),scorehome:2,scoreaway:2,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(4),scorehome:1,scoreaway:1,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(16),scorehome:2,scoreaway:0,date:'2020-09-25',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(5),scorehome:0,scoreaway:3,date:'2020-09-26',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(12),scorehome:1,scoreaway:1,date:'2020-09-26',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(10),scorehome:0,scoreaway:0,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(22),awayteam:Team.find(9),scorehome:2,scoreaway:2,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(15),scorehome:3,scoreaway:2,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(21),scorehome:3,scoreaway:2,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(13),scorehome:1,scoreaway:1,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(7),scorehome:1,scoreaway:1,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(3),scorehome:2,scoreaway:0,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(11),scorehome:6,scoreaway:1,date:'2020-10-02',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(17),scorehome:2,scoreaway:0,date:'2020-10-03',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(16),scorehome:2,scoreaway:1,date:'2020-10-03',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(20),scorehome:0,scoreaway:1,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(22),scorehome:3,scoreaway:0,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(19),scorehome:3,scoreaway:1,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(8),scorehome:1,scoreaway:0,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(21),awayteam:Team.find(7),scorehome:0,scoreaway:3,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(18),scorehome:2,scoreaway:2,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(6),scorehome:1,scoreaway:1,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(22),awayteam:Team.find(5),scorehome:1,scoreaway:1,date:'2020-10-16',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(3),scorehome:0,scoreaway:4,date:'2020-10-16',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(19),scorehome:1,scoreaway:3,date:'2020-10-17',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(14),scorehome:3,scoreaway:1,date:'2020-10-17',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(21),awayteam:Team.find(7),scorehome:2,scoreaway:3,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(12),scorehome:1,scoreaway:1,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(9),scorehome:1,scoreaway:1,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(15),scorehome:3,scoreaway:1,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(10),scorehome:1,scoreaway:3,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(13),scorehome:4,scoreaway:0,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(11),scorehome:1,scoreaway:2,date:'2020-10-23',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(6),scorehome:0,scoreaway:1,date:'2020-10-24',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(22),scorehome:4,scoreaway:0,date:'2020-10-24',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(16),stage:'8',status:'postponed')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(20),scorehome:2,scoreaway:0,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(17),scorehome:2,scoreaway:0,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(21),scorehome:3,scoreaway:0,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(18),scorehome:4,scoreaway:0,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(4),scorehome:1,scoreaway:1,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(8),scorehome:4,scoreaway:1,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(13),stage:'9',status:'postponed')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(15),scorehome:2,scoreaway:1,date:'2020-10-31',time:'17:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(3),scorehome:0,scoreaway:3,date:'2020-10-31',time:'21:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(9),scorehome:0,scoreaway:1,date:'2020-11-01',time:'13:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(21),scorehome:2,scoreaway:1,date:'2020-11-01',time:'15:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(12),scorehome:0,scoreaway:1,date:'2020-11-01',time:'15:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(22),awayteam:Team.find(19),scorehome:0,scoreaway:0,date:'2020-11-01',time:'15:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(10),scorehome:0,scoreaway:3,date:'2020-11-01',time:'15:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(14),scorehome:4,scoreaway:0,date:'2020-11-01',time:'17:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(7),scorehome:1,scoreaway:1,date:'2020-11-01',time:'21:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(21),awayteam:Team.find(6),scorehome:0,scoreaway:1,date:'2020-11-06',time:'21:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(9),scorehome:0,scoreaway:2,date:'2020-11-07',time:'17:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(5),scorehome:3,scoreaway:0,date:'2020-11-07',time:'21:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(4),scorehome:3,scoreaway:2,date:'2020-11-08',time:'13:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(16),scorehome:0,scoreaway:2,date:'2020-11-08',time:'15:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(22),scorehome:1,scoreaway:1,date:'2020-11-08',time:'15:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(18),scorehome:4,scoreaway:4,date:'2020-11-08',time:'15:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(11),scorehome:1,scoreaway:5,date:'2020-11-08',time:'15:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(8),scorehome:1,scoreaway:2,date:'2020-11-08',time:'17:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(17),scorehome:2,scoreaway:1,date:'2020-11-08',time:'21:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(14),date:'2020-11-20',time:'19:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(3),date:'2020-11-20',time:'21:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(17),date:'2020-11-21',time:'17:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(10),date:'2020-11-22',time:'21:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(12),date:'2020-11-22',time:'13:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(22),awayteam:Team.find(13),date:'2020-11-22',time:'15:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(20),date:'2020-11-22',time:'15:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(21),date:'2020-11-22',time:'15:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(7),date:'2020-11-22',time:'17:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(19),date:'2020-11-22',time:'21:00',stage:'11',status:'scheduled')

###### Create all fixtures Prod

# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(14),scorehome:0,scoreaway:0,date:'2020-08-21',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(15),scorehome:0,scoreaway:2,date:'2020-09-17',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(9),scorehome:0,scoreaway:1,date:'2020-08-22',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(2),awayteam:Team.find(3),scorehome:1,scoreaway:1,date:'2020-08-22',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(16),scorehome:2,scoreaway:2,date:'2020-08-23',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(19),scorehome:3,scoreaway:1,date:'2020-08-23',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(5),scorehome:2,scoreaway:1,date:'2020-09-15',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(13),scorehome:4,scoreaway:0,date:'2020-08-23',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(11),scorehome:2,scoreaway:1,date:'2020-08-23',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(1),awayteam:Team.find(10),scorehome:1,scoreaway:0,date:'2020-09-16',stage:'1',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(20),scorehome:4,scoreaway:1,date:'2020-08-28',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(7),scorehome:2,scoreaway:1,date:'2020-08-29',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(1),scorehome:1,scoreaway:0,date:'2020-09-10',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(8),scorehome:0,scoreaway:2,date:'2020-08-29',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(2),scorehome:0,scoreaway:1,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(18),scorehome:2,scoreaway:1,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(12),scorehome:0,scoreaway:2,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(17),scorehome:2,scoreaway:0,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(6),scorehome:0,scoreaway:1,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(4),scorehome:2,scoreaway:3,date:'2020-08-30',stage:'2',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(5),scorehome:0,scoreaway:0,date:'2020-09-11',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(8),scorehome:3,scoreaway:1,date:'2020-09-12',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(19),scorehome:2,scoreaway:0,date:'2020-09-12',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(2),awayteam:Team.find(10),scorehome:1,scoreaway:0,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(13),scorehome:0,scoreaway:2,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(16),scorehome:1,scoreaway:0,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(3),scorehome:2,scoreaway:4,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(11),scorehome:2,scoreaway:3,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(14),scorehome:2,scoreaway:1,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(1),awayteam:Team.find(4),scorehome:0,scoreaway:1,date:'2020-09-13',stage:'3',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(18),scorehome:0,scoreaway:0,date:'2020-09-18',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(12),scorehome:2,scoreaway:1,date:'2020-09-19',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(6),scorehome:2,scoreaway:1,date:'2020-09-19',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(1),scorehome:0,scoreaway:3,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(20),scorehome:1,scoreaway:0,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(9),scorehome:4,scoreaway:1,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(16),scorehome:2,scoreaway:1,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(17),scorehome:3,scoreaway:2,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(15),scorehome:2,scoreaway:2,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(2),scorehome:1,scoreaway:1,date:'2020-09-20',stage:'4',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(2),awayteam:Team.find(14),scorehome:2,scoreaway:0,date:'2020-09-25',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(3),scorehome:0,scoreaway:3,date:'2020-09-26',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(10),scorehome:1,scoreaway:1,date:'2020-09-26',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(8),scorehome:0,scoreaway:0,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(7),scorehome:2,scoreaway:2,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(13),scorehome:3,scoreaway:2,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(19),scorehome:3,scoreaway:2,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(11),scorehome:1,scoreaway:1,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(5),scorehome:1,scoreaway:1,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(1),scorehome:2,scoreaway:0,date:'2020-09-27',stage:'5',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(1),awayteam:Team.find(9),scorehome:6,scoreaway:1,date:'2020-10-02',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(15),scorehome:2,scoreaway:0,date:'2020-10-03',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(14),scorehome:2,scoreaway:1,date:'2020-10-03',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(18),scorehome:0,scoreaway:1,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(20),scorehome:3,scoreaway:0,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(17),scorehome:3,scoreaway:1,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(6),scorehome:1,scoreaway:0,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(5),scorehome:0,scoreaway:3,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(16),scorehome:2,scoreaway:2,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(4),scorehome:1,scoreaway:1,date:'2020-10-04',stage:'6',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(3),scorehome:1,scoreaway:1,date:'2020-10-16',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(1),scorehome:0,scoreaway:4,date:'2020-10-16',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(17),scorehome:1,scoreaway:3,date:'2020-10-17',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(12),scorehome:3,scoreaway:1,date:'2020-10-17',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(5),scorehome:2,scoreaway:3,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(10),scorehome:1,scoreaway:1,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(7),scorehome:1,scoreaway:1,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(13),scorehome:3,scoreaway:1,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(8),scorehome:1,scoreaway:3,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(2),awayteam:Team.find(11),scorehome:4,scoreaway:0,date:'2020-10-18',stage:'7',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(9),scorehome:1,scoreaway:2,date:'2020-10-23',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(4),scorehome:0,scoreaway:1,date:'2020-10-24',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(1),awayteam:Team.find(20),scorehome:4,scoreaway:0,date:'2020-10-24',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(14),stage:'8',status:'postponed')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(18),scorehome:2,scoreaway:0,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(15),scorehome:2,scoreaway:0,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(19),scorehome:3,scoreaway:0,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(16),scorehome:4,scoreaway:0,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(2),scorehome:1,scoreaway:1,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(6),scorehome:4,scoreaway:1,date:'2020-10-25',stage:'8',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(11),stage:'9',status:'postponed')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(13),scorehome:2,scoreaway:1,date:'2020-10-31',time:'17:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(1),scorehome:0,scoreaway:3,date:'2020-10-31',time:'21:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(15),awayteam:Team.find(7),scorehome:0,scoreaway:1,date:'2020-11-01',time:'13:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(19),scorehome:2,scoreaway:1,date:'2020-11-01',time:'15:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(10),scorehome:0,scoreaway:1,date:'2020-11-01',time:'15:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(17),scorehome:0,scoreaway:0,date:'2020-11-01',time:'15:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(8),scorehome:0,scoreaway:3,date:'2020-11-01',time:'15:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(12),scorehome:4,scoreaway:0,date:'2020-11-01',time:'17:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(2),awayteam:Team.find(5),scorehome:1,scoreaway:1,date:'2020-11-01',time:'21:00',stage:'9',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(19),awayteam:Team.find(4),scorehome:0,scoreaway:1,date:'2020-11-06',time:'21:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(12),awayteam:Team.find(7),scorehome:0,scoreaway:2,date:'2020-11-07',time:'17:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(1),awayteam:Team.find(3),scorehome:3,scoreaway:0,date:'2020-11-07',time:'21:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(2),scorehome:3,scoreaway:2,date:'2020-11-08',time:'13:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(17),awayteam:Team.find(14),scorehome:0,scoreaway:2,date:'2020-11-08',time:'15:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(10),awayteam:Team.find(20),scorehome:1,scoreaway:1,date:'2020-11-08',time:'15:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(11),awayteam:Team.find(16),scorehome:4,scoreaway:4,date:'2020-11-08',time:'15:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(18),awayteam:Team.find(9),scorehome:1,scoreaway:5,date:'2020-11-08',time:'15:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(8),awayteam:Team.find(6),scorehome:1,scoreaway:2,date:'2020-11-08',time:'17:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(5),awayteam:Team.find(15),scorehome:2,scoreaway:1,date:'2020-11-08',time:'21:00',stage:'10',status:'played')
# Fixture.create(season:Season.find(1),hometeam:Team.find(3),awayteam:Team.find(12),date:'2020-11-20',time:'19:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(6),awayteam:Team.find(1),date:'2020-11-20',time:'21:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(13),awayteam:Team.find(15),date:'2020-11-21',time:'17:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(4),awayteam:Team.find(8),date:'2020-11-22',time:'21:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(14),awayteam:Team.find(10),date:'2020-11-22',time:'13:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(20),awayteam:Team.find(11),date:'2020-11-22',time:'15:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(16),awayteam:Team.find(18),date:'2020-11-22',time:'15:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(7),awayteam:Team.find(19),date:'2020-11-22',time:'15:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(9),awayteam:Team.find(5),date:'2020-11-22',time:'17:00',stage:'11',status:'scheduled')
# Fixture.create(season:Season.find(1),hometeam:Team.find(2),awayteam:Team.find(17),date:'2020-11-22',time:'21:00',stage:'11',status:'scheduled')

###### Create all goals local ######

# Goal.create(fixture:Fixture.find(4),team:Team.find(17),minute:'6')
# Goal.create(fixture:Fixture.find(4),team:Team.find(17),minute:'75')

# Goal.create(fixture:Fixture.find(5),team:Team.find(11),minute:'22')

# Goal.create(fixture:Fixture.find(6),team:Team.find(4),minute:'40')
# Goal.create(fixture:Fixture.find(6),team:Team.find(5),minute:'74')

# Goal.create(fixture:Fixture.find(7),team:Team.find(8),minute:'5')
# Goal.create(fixture:Fixture.find(7),team:Team.find(8),minute:'21')
# Goal.create(fixture:Fixture.find(7),team:Team.find(18),minute:'45+2')
# Goal.create(fixture:Fixture.find(7),team:Team.find(18),minute:'55')

# Goal.create(fixture:Fixture.find(8),team:Team.find(21),minute:'30')
# Goal.create(fixture:Fixture.find(8),team:Team.find(19),minute:'51')
# Goal.create(fixture:Fixture.find(8),team:Team.find(19),minute:'60')
# Goal.create(fixture:Fixture.find(8),team:Team.find(19),minute:'87')

# Goal.create(fixture:Fixture.find(9),team:Team.find(9),minute:'39')
# Goal.create(fixture:Fixture.find(9),team:Team.find(9),minute:'59')
# Goal.create(fixture:Fixture.find(9),team:Team.find(7),minute:'82')

# Goal.create(fixture:Fixture.find(10),team:Team.find(20),minute:'8')
# Goal.create(fixture:Fixture.find(10),team:Team.find(20),minute:'31')
# Goal.create(fixture:Fixture.find(10),team:Team.find(20),minute:'69')
# Goal.create(fixture:Fixture.find(10),team:Team.find(20),minute:'84')

# Goal.create(fixture:Fixture.find(11),team:Team.find(13),minute:'11')
# Goal.create(fixture:Fixture.find(11),team:Team.find(10),minute:'23')
# Goal.create(fixture:Fixture.find(11),team:Team.find(10),minute:'75')

# Goal.create(fixture:Fixture.find(12),team:Team.find(3),minute:'90+3')

# Goal.create(fixture:Fixture.find(13),team:Team.find(22),minute:'14')
# Goal.create(fixture:Fixture.find(13),team:Team.find(7),minute:'39')
# Goal.create(fixture:Fixture.find(13),team:Team.find(7),minute:'45')
# Goal.create(fixture:Fixture.find(13),team:Team.find(7),minute:'45+1')
# Goal.create(fixture:Fixture.find(13),team:Team.find(7),minute:'66')

# Goal.create(fixture:Fixture.find(14),team:Team.find(5),minute:'22')
# Goal.create(fixture:Fixture.find(14),team:Team.find(5),minute:'77')
# Goal.create(fixture:Fixture.find(14),team:Team.find(9),minute:'90+1')

# Goal.create(fixture:Fixture.find(15),team:Team.find(13),minute:'57')

# Goal.create(fixture:Fixture.find(16),team:Team.find(10),minute:'37')
# Goal.create(fixture:Fixture.find(16),team:Team.find(10),minute:'59')

# Goal.create(fixture:Fixture.find(17),team:Team.find(4),minute:'32')

# Goal.create(fixture:Fixture.find(18),team:Team.find(16),minute:'11')
# Goal.create(fixture:Fixture.find(18),team:Team.find(16),minute:'27')
# Goal.create(fixture:Fixture.find(18),team:Team.find(20),minute:'57')

# Goal.create(fixture:Fixture.find(19),team:Team.find(14),minute:'25')
# Goal.create(fixture:Fixture.find(19),team:Team.find(14),minute:'27')

# Goal.create(fixture:Fixture.find(20),team:Team.find(17),minute:'18')
# Goal.create(fixture:Fixture.find(20),team:Team.find(17),minute:'51')

# Goal.create(fixture:Fixture.find(21),team:Team.find(8),minute:'22')

# Goal.create(fixture:Fixture.find(22),team:Team.find(6),minute:'20')
# Goal.create(fixture:Fixture.find(22),team:Team.find(6),minute:'27')
# Goal.create(fixture:Fixture.find(22),team:Team.find(15),minute:'45+1')
# Goal.create(fixture:Fixture.find(22),team:Team.find(6),minute:'80')
# Goal.create(fixture:Fixture.find(22),team:Team.find(15),minute:'89')


# Goal.create(fixture:Fixture.find(24),team:Team.find(9),minute:'18')
# Goal.create(fixture:Fixture.find(24),team:Team.find(9),minute:'50')
# Goal.create(fixture:Fixture.find(24),team:Team.find(9),minute:'64')
# Goal.create(fixture:Fixture.find(24),team:Team.find(10),minute:'69')

# Goal.create(fixture:Fixture.find(25),team:Team.find(17),minute:'57')
# Goal.create(fixture:Fixture.find(25),team:Team.find(17),minute:'82')

# Goal.create(fixture:Fixture.find(26),team:Team.find(4),minute:'88')

# Goal.create(fixture:Fixture.find(27),team:Team.find(15),minute:'42')
# Goal.create(fixture:Fixture.find(27),team:Team.find(15),minute:'90+5')

# Goal.create(fixture:Fixture.find(28),team:Team.find(11),minute:'55')

# Goal.create(fixture:Fixture.find(29),team:Team.find(5),minute:'12')
# Goal.create(fixture:Fixture.find(29),team:Team.find(20),minute:'36')
# Goal.create(fixture:Fixture.find(29),team:Team.find(5),minute:'39')
# Goal.create(fixture:Fixture.find(29),team:Team.find(20),minute:'55')
# Goal.create(fixture:Fixture.find(29),team:Team.find(5),minute:'72')
# Goal.create(fixture:Fixture.find(29),team:Team.find(5),minute:'90+7')

# Goal.create(fixture:Fixture.find(30),team:Team.find(19),minute:'13')
# Goal.create(fixture:Fixture.find(30),team:Team.find(13),minute:'31')
# Goal.create(fixture:Fixture.find(30),team:Team.find(13),minute:'34')
# Goal.create(fixture:Fixture.find(30),team:Team.find(13),minute:'63')
# Goal.create(fixture:Fixture.find(30),team:Team.find(19),minute:'90+3')

# Goal.create(fixture:Fixture.find(31),team:Team.find(8),minute:'5')
# Goal.create(fixture:Fixture.find(31),team:Team.find(16),minute:'61')
# Goal.create(fixture:Fixture.find(31),team:Team.find(8),minute:'65')

# Goal.create(fixture:Fixture.find(32),team:Team.find(6),minute:'31')

###### Create all goals prod ######

Goal.create(fixture:Fixture.find(2),team:Team.find(15),minute:'6')
Goal.create(fixture:Fixture.find(2),team:Team.find(15),minute:'75')

Goal.create(fixture:Fixture.find(3),team:Team.find(9),minute:'22')

Goal.create(fixture:Fixture.find(4),team:Team.find(2),minute:'40')
Goal.create(fixture:Fixture.find(4),team:Team.find(3),minute:'74')

Goal.create(fixture:Fixture.find(5),team:Team.find(6),minute:'5')
Goal.create(fixture:Fixture.find(5),team:Team.find(6),minute:'21')
Goal.create(fixture:Fixture.find(5),team:Team.find(16),minute:'45+2')
Goal.create(fixture:Fixture.find(5),team:Team.find(16),minute:'55')

Goal.create(fixture:Fixture.find(6),team:Team.find(19),minute:'30')
Goal.create(fixture:Fixture.find(6),team:Team.find(17),minute:'51')
Goal.create(fixture:Fixture.find(6),team:Team.find(17),minute:'60')
Goal.create(fixture:Fixture.find(6),team:Team.find(17),minute:'87')

Goal.create(fixture:Fixture.find(7),team:Team.find(7),minute:'39')
Goal.create(fixture:Fixture.find(7),team:Team.find(7),minute:'59')
Goal.create(fixture:Fixture.find(7),team:Team.find(5),minute:'82')

Goal.create(fixture:Fixture.find(8),team:Team.find(18),minute:'8')
Goal.create(fixture:Fixture.find(8),team:Team.find(18),minute:'31')
Goal.create(fixture:Fixture.find(8),team:Team.find(18),minute:'69')
Goal.create(fixture:Fixture.find(8),team:Team.find(18),minute:'84')

Goal.create(fixture:Fixture.find(9),team:Team.find(11),minute:'11')
Goal.create(fixture:Fixture.find(9),team:Team.find(8),minute:'23')
Goal.create(fixture:Fixture.find(9),team:Team.find(8),minute:'75')

Goal.create(fixture:Fixture.find(10),team:Team.find(1),minute:'90+3')

Goal.create(fixture:Fixture.find(11),team:Team.find(20),minute:'14')
Goal.create(fixture:Fixture.find(11),team:Team.find(5),minute:'39')
Goal.create(fixture:Fixture.find(11),team:Team.find(5),minute:'45')
Goal.create(fixture:Fixture.find(11),team:Team.find(5),minute:'45+1')
Goal.create(fixture:Fixture.find(11),team:Team.find(5),minute:'66')

Goal.create(fixture:Fixture.find(12),team:Team.find(3),minute:'22')
Goal.create(fixture:Fixture.find(12),team:Team.find(3),minute:'77')
Goal.create(fixture:Fixture.find(12),team:Team.find(7),minute:'90+1')

Goal.create(fixture:Fixture.find(13),team:Team.find(11),minute:'57')

Goal.create(fixture:Fixture.find(14),team:Team.find(8),minute:'37')
Goal.create(fixture:Fixture.find(14),team:Team.find(8),minute:'59')

Goal.create(fixture:Fixture.find(15),team:Team.find(2),minute:'32')

Goal.create(fixture:Fixture.find(16),team:Team.find(14),minute:'11')
Goal.create(fixture:Fixture.find(16),team:Team.find(14),minute:'27')
Goal.create(fixture:Fixture.find(16),team:Team.find(18),minute:'57')

Goal.create(fixture:Fixture.find(17),team:Team.find(12),minute:'25')
Goal.create(fixture:Fixture.find(17),team:Team.find(12),minute:'27')

Goal.create(fixture:Fixture.find(18),team:Team.find(15),minute:'18')
Goal.create(fixture:Fixture.find(18),team:Team.find(15),minute:'51')

Goal.create(fixture:Fixture.find(19),team:Team.find(6),minute:'22')

Goal.create(fixture:Fixture.find(20),team:Team.find(4),minute:'20')
Goal.create(fixture:Fixture.find(20),team:Team.find(4),minute:'27')
Goal.create(fixture:Fixture.find(20),team:Team.find(13),minute:'45+1')
Goal.create(fixture:Fixture.find(20),team:Team.find(4),minute:'80')
Goal.create(fixture:Fixture.find(20),team:Team.find(13),minute:'89')


Goal.create(fixture:Fixture.find(22),team:Team.find(7),minute:'18')
Goal.create(fixture:Fixture.find(22),team:Team.find(7),minute:'50')
Goal.create(fixture:Fixture.find(22),team:Team.find(7),minute:'64')
Goal.create(fixture:Fixture.find(22),team:Team.find(8),minute:'69')

Goal.create(fixture:Fixture.find(23),team:Team.find(15),minute:'57')
Goal.create(fixture:Fixture.find(23),team:Team.find(15),minute:'82')

Goal.create(fixture:Fixture.find(24),team:Team.find(2),minute:'88')

Goal.create(fixture:Fixture.find(25),team:Team.find(13),minute:'42')
Goal.create(fixture:Fixture.find(25),team:Team.find(13),minute:'90+5')

Goal.create(fixture:Fixture.find(26),team:Team.find(9),minute:'55')

Goal.create(fixture:Fixture.find(27),team:Team.find(3),minute:'12')
Goal.create(fixture:Fixture.find(27),team:Team.find(18),minute:'36')
Goal.create(fixture:Fixture.find(27),team:Team.find(3),minute:'39')
Goal.create(fixture:Fixture.find(27),team:Team.find(18),minute:'55')
Goal.create(fixture:Fixture.find(27),team:Team.find(3),minute:'72')
Goal.create(fixture:Fixture.find(27),team:Team.find(3),minute:'90+7')

Goal.create(fixture:Fixture.find(28),team:Team.find(17),minute:'13')
Goal.create(fixture:Fixture.find(28),team:Team.find(11),minute:'31')
Goal.create(fixture:Fixture.find(28),team:Team.find(11),minute:'34')
Goal.create(fixture:Fixture.find(28),team:Team.find(11),minute:'63')
Goal.create(fixture:Fixture.find(28),team:Team.find(17),minute:'90+3')

Goal.create(fixture:Fixture.find(29),team:Team.find(6),minute:'5')
Goal.create(fixture:Fixture.find(29),team:Team.find(14),minute:'61')
Goal.create(fixture:Fixture.find(29),team:Team.find(6),minute:'65')

Goal.create(fixture:Fixture.find(30),team:Team.find(4),minute:'31')

